[package]
name = "aoc-2020-05a"
version = "0.1.0"
authors = ["Mikael Auno <mikael@auno.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
